name: Run

on:
  workflow_dispatch:
    inputs:
      deb:
        description: "Direct URL to deb file"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg zip

      - name: Download and extract DEB
        run: |
          curl -L -o app.deb "${{ github.event.inputs.deb }}"
          mkdir -p extracted
          dpkg-deb -X app.deb extracted
          dpkg-deb -e app.deb extracted/DEBIAN

      - name: Prepare IPA structure
        run: |
          mkdir -p ipa/Payload
          APP_PATH=$(find extracted -name "*.app" | head -n 1)

          if [ -z "$APP_PATH" ]; then
            echo "No .app directory found in extracted DEB."
            exit 1
          fi

          mv "$APP_PATH" ipa/Payload/

      - name: Create IPA file
        run: |
          cd ipa
          zip -r App.ipa Payload
          mv App.ipa ../

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: App
          path: App.ipa
